spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/twitter_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8082}

spring.servlet.multipart.max-file-size=70MB
spring.servlet.multipart.max-request-size=70MB

